#!/usr/bin/php
<?php

if (1 == count($argv) || (in_array('-h', $argv, true) || in_array('--help', $argv, true))) {
    echo(sprintf(
        "usage: liccheck [-h] [-s STRATEGY_JSON_FILE] [-r [COMPOSER_PATH=composer]]
            
Check license of packages and their dependencies.

required arguments:
  -s STRATEGY_JSON_FILE strategy json file

optional arguments:
  -h, --help            show this help message and exit
  -r [COMPOSER_PATH]    path/to/composer binary
"));
    exit(0);
}

if (!in_array('-s', $argv)) {
    echo(sprintf('Need strategy file%s%s%s', PHP_EOL, json_encode([
        "Licenses"            => [
            "authorized_licenses"   => [],
            "unauthorized_licenses" => []
        ],
        "Authorized Packages" => []
    ], JSON_PRETTY_PRINT), PHP_EOL));
    exit(1);
}

$licensesIndex = (int)array_search('-s', $argv, true);
$licensesPath  = $argv[$licensesIndex + 1];
$licenses      = file_get_contents($licensesPath);
if (false === $licenses) {
    echo(sprintf('Error reading "%s" strategy file%s', $licensesPath, PHP_EOL));
    exit(1);
}

$licenses = json_decode($licenses, true);
if (JSON_ERROR_NONE !== json_last_error()) {
    echo(sprintf('Error decoding "%s"%s', $licensesPath, PHP_EOL));
    exit(1);
}

echo('gathering licenses...');
$dependenciesIndex = (int)array_search('-r', $argv, true);
$command           = sprintf('%s licenses --format json', $dependenciesIndex <= 0 ? 'composer' : $argv[$dependenciesIndex + 1]);
exec($command, $returnContent, $returnCode);
if (0 !== ((int)$returnCode)) {
    echo(sprintf('Failed executing "%s" command%s', $command, PHP_EOL));
    exit(1);
}

$dependencies = json_decode(join('', $returnContent), true);
if (false === $dependencies) {
    echo(sprintf('Error decoding result of "%s" command%s', $command, PHP_EOL));
    exit(1);
} else if (!array_key_exists('dependencies', $dependencies)) {
    echo(sprintf('Need "%s" key in result of "%s" command%s', 'dependencies', $command, PHP_EOL));
    exit(1);
} else {
    $dependencies = $dependencies['dependencies'];
}

// Remove Authorized Packages from dependencies
echo('check authorized packages...');
foreach ($licenses['Authorized Packages'] as $authorizedPackage) {
    foreach ($dependencies as $dependency => $value) {
        if ($authorizedPackage === $dependency) {
            unset($dependencies[$dependency]);
        }
    }
}

// Validate Authorized Licenses and Unauthorized Licenses
$intersection = array_intersect(
    $licenses['Licenses']['authorized_licenses'],
    $licenses['Licenses']['unauthorized_licenses']
);
if (!empty($intersection)) {
    print_r(sprintf(
        'Duplicated Authorized and Unauthorized Licenses%s%s',
        PHP_EOL,
        json_encode($intersection, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
    ));
    exit(1);
}

// Prepare Unauthorized Licenses
$unauthorizedLicenses = $licenses['Licenses']['unauthorized_licenses'];
foreach ($dependencies as $dependency) {
    $unauthorizedLicenses = array_merge($unauthorizedLicenses, $dependency['license']);
}
$unauthorizedLicenses = array_unique($unauthorizedLicenses);

// Remove Authorized Licenses from dependencies
foreach ($licenses['Licenses']['authorized_licenses'] as $authorizedLicense) {
    if (in_array($authorizedLicense, $unauthorizedLicenses, true)) {
        unset($unauthorizedLicenses[array_search($authorizedLicense, $unauthorizedLicenses)]);
    }
    foreach ($dependencies as $dependency => $value) {
        if (in_array($authorizedLicense, $value['license'], true)) {
            unset($dependencies[$dependency]);
            break;
        }
    }
}

// Remove Unauthorized Licenses found from dependencies and add to $unauthorizedLicensesFound array
echo('check unauthorized packages...');
$unauthorizedLicensesFound = [];
foreach ($unauthorizedLicenses as $unauthorizedLicense) {
    foreach ($dependencies as $dependency => $value) {
        if (in_array($unauthorizedLicense, $value['license'], true)) {
            $unauthorizedLicensesFound[$unauthorizedLicense][] = $dependency;
            unset($dependencies[$dependency]);
        }
    }
}

if (!empty($unauthorizedLicensesFound)) {
    print_r(sprintf(
        'Unauthorized Licenses found%s%s',
        PHP_EOL,
        json_encode($unauthorizedLicensesFound, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
    ));
    exit(1);
}

exit(0);
