name: Publish
on: [push, pull_request]
jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish package
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=ticdenis&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/ticdenis/liccheck"}}'
